version: '3.9'

networks:
  app-network:
  db-network:

volumes:
  db-data:
  mq-data:

services:
  app:
    container_name: 'listing_app'
    build:
      context: .
      dockerfile: docker/php/local/Dockerfile
    environment:
      XDEBUG_MODE: 'debug,coverage,develop'
      XDEBUG_CONFIG: 'client_host=host.docker.internal,client_port=9003'
      PHP_IDE_CONFIG: 'serverName=ListingServer'
      APP_RUNTIME: 'Runtime\Swoole\Runtime'
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/var/www/html/:cached
    depends_on:
      - db
      - db_test
      - rabbitmq
    networks:
      - app-network
      - db-network

  db:
    container_name: 'listing_db'
    image: percona:8
    environment:
      MYSQL_DATABASE: 'listing'
      MYSQL_USER: 'listing'
      MYSQL_PASSWORD: 'listing'
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - db-network

  db_test:
    container_name: 'listing_test_db'
    image: percona:8
    environment:
      MYSQL_DATABASE: 'listing_test'
      MYSQL_USER: 'listing'
      MYSQL_PASSWORD: 'listing'
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
    networks:
      - db-network

  rabbitmq:
    container_name: 'listing_mq'
    image: rabbitmq:3.11-management-alpine
    ports:
      - 8082:15672
    environment:
      RABBITMQ_DEFAULT_USER: listing
      RABBITMQ_DEFAULT_PASS: listing
    volumes:
      - mq-data:/var/lib/rabbitmq
    networks:
      - app-network

  phpmyadmin:
    container_name: 'listing_pma'
    image: phpmyadmin:latest
    environment:
      PMA_HOSTS: 'db,db_test'
      PMA_USER: 'listing'
      PMA_PASSWORD: 'listing'
    ports:
      - "8081:80"
    networks:
      - db-network
    depends_on:
      - db
      - db_test