parameters:
    container.dumper.inline_factories: true

services:
    _defaults:
        autowire: true
        autoconfigure: true

    Listing\Framework\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    Listing\Shared\Infrastructure\Database\CycleDatabaseManagerFactory: ~
    Listing\Shared\Infrastructure\Database\CycleORMFactory: ~
    Listing\Shared\Infrastructure\Database\CycleMigratorFactory: ~

    Cycle\Database\DatabaseProviderInterface:
        class: Cycle\Database\DatabaseManager
        factory: '@Listing\Shared\Infrastructure\Database\CycleDatabaseManagerFactory'
        arguments:
            $dsn: '%env(string:DATABASE_DSN)%'
            $user: '%env(string:DATABASE_USERNAME)%'
            $password: '%env(string:DATABASE_PASSWORD)%'

    Cycle\ORM\ORMInterface:
        class: Cycle\ORM\ORM
        factory: '@Listing\Shared\Infrastructure\Database\CycleORMFactory'
        arguments:
            $dbal: '@Cycle\Database\DatabaseProviderInterface'

    Cycle\Migrations\Migrator:
        factory: '@Listing\Shared\Infrastructure\Database\CycleMigratorFactory'
        arguments:
            $dbal: '@Cycle\Database\DatabaseProviderInterface'
            $projectDir: '%kernel.project_dir%'

    Listing\Shared\Infrastructure\Symfony\CleanORMHeapRequestFinishListener:
        tags:
            - { name: kernel.event_listener, event: kernel.finish_request, priority: -256 }
        arguments:
            $orm: '@Cycle\ORM\ORMInterface'
